
import { poppins } from './fonts'
import './globals.css'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='' >
      <body className={`${poppins.variable} font-poppins max-w-screen-lg flex flex-col justify-between my-0 mx-auto`}>{children}</body>
    </html>
  )
}
